name: 'Feature Request'
description: 'Suggest a new feature or enhancement for the AI Email Marketing System'
title: '[FEATURE] '
labels: ['enhancement', 'needs-review']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make the AI Email Marketing System better.

        Before submitting, please check if this feature has already been requested in our [issue tracker](https://github.com/aimnovo/email-marketing/issues).

  - type: textarea
    id: summary
    attributes:
      label: 'Feature Summary'
      description: 'A clear and concise description of the feature you want to see added.'
      placeholder: 'Briefly describe the feature...'
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 'Problem Statement'
      description: 'What problem does this feature solve? What need does it address?'
      placeholder: 'Describe the problem or need this feature would address...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 'Proposed Solution'
      description: 'Describe the solution you would like to see implemented.'
      placeholder: 'Describe your proposed solution in detail...'
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 'Feature Category'
      description: 'Which area does this feature belong to?'
      options:
        - AI/Machine Learning
        - Email Templates
        - Analytics & Reporting
        - User Interface
        - API & Integrations
        - Authentication & Security
        - Performance & Optimization
        - Database & Storage
        - Automation & Workflows
        - Import/Export
        - Notifications
        - Admin & Management
        - Mobile Support
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 'Priority'
      description: 'How important is this feature to you?'
      options:
        - Low (Nice to have)
        - Medium (Would improve workflow)
        - High (Important for productivity)
        - Critical (Blocking current work)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 'Use Cases'
      description: 'Describe specific scenarios where this feature would be useful.'
      placeholder: |
        1. As a [type of user], I want to [action] so that [benefit]
        2. When [situation], I need to [action] because [reason]
        3. ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives Considered'
      description: 'Describe any alternative solutions or features you have considered.'
      placeholder: 'What other approaches did you consider?'

  - type: textarea
    id: mockups
    attributes:
      label: 'Mockups/Wireframes'
      description: 'If applicable, add mockups, wireframes, or screenshots to help explain your feature.'
      placeholder: 'Drag and drop images here or paste them...'

  - type: textarea
    id: technical
    attributes:
      label: 'Technical Considerations'
      description: 'Any technical details, constraints, or implementation ideas?'
      placeholder: 'Share any technical thoughts or considerations...'

  - type: dropdown
    id: scope
    attributes:
      label: 'Implementation Scope'
      description: 'How complex do you think this feature would be to implement?'
      options:
        - Small (Few hours of work)
        - Medium (Few days of work)
        - Large (Few weeks of work)
        - Extra Large (Few months of work)
        - Unknown
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: 'Expected Impact'
      description: 'What areas would this feature impact? (Select all that apply)'
      options:
        - label: User Experience
        - label: Performance
        - label: Security
        - label: Scalability
        - label: Maintainability
        - label: API Compatibility
        - label: Database Schema
        - label: Third-party Integrations
        - label: Documentation

  - type: textarea
    id: additional
    attributes:
      label: 'Additional Context'
      description: 'Add any other context, links, or examples about the feature request here.'
      placeholder: 'Any additional information that might help...'

  - type: checkboxes
    id: terms
    attributes:
      label: 'Checklist'
      description: 'Please confirm the following:'
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided clear use cases and problem description
          required: true
        - label: I understand this is a suggestion and may not be implemented immediately
          required: true
        - label: I am willing to provide feedback during the implementation process
          required: false
        - label: I am interested in contributing to the implementation
          required: false
