name: 'Question or Support'
description: 'Ask a question or get support for the AI Email Marketing System'
title: '[QUESTION] '
labels: ['question', 'support']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Welcome! We're here to help you with the AI Email Marketing System. 

        Before asking, please check our [documentation](https://aimnovo.github.io/email-marketing/) and [existing issues](https://github.com/aimnovo/email-marketing/issues).

  - type: dropdown
    id: question-type
    attributes:
      label: 'Question Type'
      description: 'What type of question or support do you need?'
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - API & Integration
        - Troubleshooting
        - Performance
        - Security
        - Commercial Use
        - Contributing
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 'Your Question'
      description: 'Please describe your question or issue in detail.'
      placeholder: 'Ask your question here...'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 'Context'
      description: 'Provide any relevant context, what you are trying to achieve, or what you have already tried.'
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - Any error messages you're seeing?
        - Links to relevant documentation you've read?

  - type: textarea
    id: environment
    attributes:
      label: 'Environment Information'
      description: 'Please provide details about your environment (if relevant)'
      placeholder: |
        - OS: [e.g., macOS 13.0, Ubuntu 20.04, Windows 11]
        - Node.js Version: [e.g., 18.17.0]
        - Database: [e.g., PostgreSQL 15]
        - Browser: [e.g., Chrome 119, Firefox 118]
        - Version: [e.g., v1.0.0, main branch]
      render: markdown

  - type: textarea
    id: code-example
    attributes:
      label: 'Code Example'
      description: 'If relevant, provide a code example or configuration snippet'
      placeholder: 'Paste your code here...'
      render: javascript

  - type: dropdown
    id: urgency
    attributes:
      label: 'Urgency'
      description: 'How urgent is this question?'
      options:
        - Low (General inquiry)
        - Medium (Affecting development)
        - High (Blocking progress)
        - Critical (Production issue)
    validations:
      required: true

  - type: checkboxes
    id: searched
    attributes:
      label: 'Pre-submission Checklist'
      description: 'Please confirm you have done the following:'
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues
          required: true
        - label: I have provided sufficient context
          required: true
        - label: This is not a bug report (use bug report template instead)
          required: true

  - type: markdown
    attributes:
      value: |
        ## 📞 Additional Support Options

        ### Commercial Support
        For commercial use and priority support, contact:
        - **Email:** ismail@aimnovo.com
        - **Company:** AimNovo.com
        - **AI Platform:** AimNexus.ai

        ### Community Resources
        - **Documentation:** [GitHub Pages](https://aimnovo.github.io/email-marketing/)
        - **Contributing:** [Contributing Guide](./CONTRIBUTING.md)
        - **License:** [MIT License](./LICENSE)

        ### Response Times
        - **Questions:** 1-3 business days
        - **Commercial Support:** 24-48 hours
        - **Critical Issues:** As soon as possible

        Thank you for using the AI Email Marketing System! 🚀
